import React, { Component, useRef } from "react";

/**
 * Secci√≥n 8: Debuggin y control de Errores
 */
class LimiteErrores extends Component {
  state = {
    tieneError: false
  };
  componentDidCatch(error, errorInfo) {
    this.setState({ tieneError: true, error });
  }

  render() {
    const { tieneError, error, errorInfo } = this.state;
    if (tieneError) {
      return (
        <div>
          <p>UPs! Ocurri√≥ un error inesperado en la aplicaci√≥n :/ </p>
          <h2>{!!error && error.toString()}</h2>
        </div>
      );
    }
    return this.props.children;
  }
}

class FailedButton extends Component {
  state = {
    dispararError: false
  };
  dispararError = () => this.setState({ dispararError: true });

  render() {
    if (this.state.dispararError) {
      throw new Error("Lo siento he fallado Ô∏è‚Äçüî•Ô∏è‚Äçüî•Ô∏è‚Äçüî•");
    }
    return <button onClick={this.dispararError}>Button with Bug</button>;
  }
}

const Section8 = () => {
  return (
    <>
      <h1 className="section-title">
        Secci√≥n 8: Debuggin y control de Errores
      </h1>
      <p>El poderoso Chrome DevTools</p>
      <LimiteErrores>
        <FailedButton />
      </LimiteErrores>
    </>
  );
};

export default Section8;
